homebridge:
  build: ./homebridge
  ports:
    - "51826:51826"
  net: host
  volumes:
    - ./homebridge/config.json:/root/.homebridge/config.json
    - ./homebridge/plugins.txt:/root/.homebridge/plugins.txt
homecontroller-gateway:
  build: ./gateway
  volumes:
    - "./gateway/src:/app/src"
    - "./gateway/package.json:/app/package.json"
  ports:
    - "80:3000"
  devices:
    - "/dev/i2c-1:/dev/i2c-1"